[package]
name = "gzcsv"
version = "0.1.0"
authors = ["Mike Cooper <mythmon@gmail.com>"]

[dependencies]
csv = "1.0.0-beta.5"
libflate = "*"
serde = "*"
serde_derive = "*"
chrono = { version = "0.4", features = ["serde"] }
